filegroup(
    name = "all",
    srcs = [
        "//toolchain/hermetic_cc_toolchain/wrappers/posix:all",
        "//toolchain/hermetic_cc_toolchain/wrappers/windows:all",
    ],
    visibility = ["//visibility:public"],
)
