# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
 #  -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
 #  -   id: destroyed-simlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: no-commit-to-branch
    -   id: pretty-format-json
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v15.0.6'
    hooks:
        - id: clang-format

# - repo: https://github.com/jumanjihouse/pre-commit-hooks
#   rev: 3.0.0
#   hooks:
#     - id: forbid-binary
#     - id: markdownlint # Configure in .mdlrc
