package(default_visibility = ["//visibility:private"])

py_library(
    name = "config",
    srcs = ["formak/compiler/config.py"],
    imports = ["."],
    visibility = ["//visibility:public"],
)

py_library(
    name = "compiler",
    srcs = ["formak/compiler/__init__.py"],
    imports = ["."],
    visibility = ["//visibility:public"],
)
