package(default_visibility = ["//visibility:private"])

py_library(
    name = "compiler",
    srcs = [],
    imports = ["."],
    visibility = ["//formak:__pkg__"],
    deps = [
        "//compiler/cpp:basic-block",
        # "//compiler/cpp:compiler",
        "//compiler/cpp:config",
        "//compiler/py:basic-block",
        # "//compiler/py:compiler",
        "//compiler/py:config",
    ],
)
