load("//featuretests:test_deps.bzl", "CC_FEATURE_TEST_DEPS")

cc_test(
    name = "cpp11",
    srcs = ["cpp11.cpp"],
    deps = CC_FEATURE_TEST_DEPS,
)

cc_test(
    name = "cpp14",
    srcs = ["cpp14.cpp"],
    deps = CC_FEATURE_TEST_DEPS,
)

cc_test(
    name = "cpp17",
    srcs = ["cpp17.cpp"],
    deps = CC_FEATURE_TEST_DEPS,
)
