make format ; 
flake8 $(ag --python -g ".*" compiler/ runtime/ common/ featuretests/ frontend/ backend/)  --config=config/setup.cfg ; 
bazel test //backend/... //compiler/... //config/... //common/... //demo/... //experimental/... //featuretests/... //frontend/... //languagesupport/... //middleend/... //runtime/...
