make format ;
flake8 --config=common/setup.cfg  featuretests/ cpp/ py/ languagesupport/ | grep -v "ui.py.*unused" | grep "unused";
bazel test //featuretests/... //cpp/... //py/... //languagesupport/...
