make format ; 
flake8 $(ag --python -g ".*" compiler/ runtime/) --config=config/setup.cfg ; 
bazel test //backend/... //compiler/... //config/... //demo/... //experimental/... //featuretests/... //frontend/... //languagesupport/... //middleend/... //runtime/...
