package(default_visibility = ["//visibility:private"])

filegroup(
    name = "templates",
    srcs = glob(
        [
            "formak/templates/*.hpp",
            "formak/templates/*.cpp",
            "formak/templates/test/*.cpp",
        ],
        allow_empty = False,
    ),
    visibility = ["//visibility:public"],
)
