cc_library(
    name = "managed-filter",
    hdrs = [
        "include/formak/runtime/ManagedFilter.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [],
)
